version: 2.1
executors:
  base:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/spatialcurrent/go-math
jobs:
  pre_deps_golang:
    executor: base
    steps:
      - checkout
      - run: make deps_go
      - run: sudo chown -R circleci /go/src
      - save_cache:
          key: v1-go-src-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/src
  test_go:
    executor: base
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - v1-go-src-{{ .Branch }}-{{ .Revision }}
      - run: make deps_go_test
      - run: make test_go
      - run: make imports
      - run: git diff --exit-code
workflows:
  main:
    jobs:
      - pre_deps_golang
      - test_go:
          requires:
            - pre_deps_golang
